In [1]:
# import required libraries
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score, roc_auc_score, roc_curve, classification_report, confusion_matrix, ConfusionMatrixDisplay, auc
from xgboost import XGBClassifier

In [2]:
# load the clean dataset
churn_df = pd.read_csv('../data/churn_cleaned.csv')
churn_df.head()

,state,account length,area code,phone number,international plan,voice mail plan,number vmail messages,total day minutes,total day calls,total day charge,...,total eve calls,total eve charge,total night minutes,total night calls,total night charge,total intl minutes,total intl calls,total intl charge,customer service calls,churn
0,16,128,415,1926,NaN,NaN,25,265.1,110,45.07,...,99,16.78,244.7,91,11.01,10.0,3,2.70,1,0
1,35,107,415,1575,NaN,NaN,26,161.6,123,27.47,...,103,16.62,254.4,103,11.45,13.7,3,3.70,1,0
2,31,137,415,1117,NaN,NaN,0,243.4,114,41.38,...,110,10.30,162.6,104,7.32,12.2,5,3.29,0,0
3,35,84,408,1707,NaN,NaN,0,299.4,71,50.90,...,88,5.26,196.9,89,8.86,6.6,7,1.78,2,0
4,36,75,415,110,NaN,NaN,0,166.7,113,28.34,...,122,12.61,186.9,121,8.41,10.1,3,2.73,3,0

In [4]:
# # define X and y variables
X = churn_df.drop(columns='churn', axis=1)
y = churn_df['churn']

# split into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# # scale the train and test features
# scaler = StandardScaler()
# X_train_scaled = scaler.fit_transform(X_train)
# X_test_scaled = scaler.transform(X_test)

# display the shape of thr train and test sets
print("Shape of X_train:", X_train.shape)
print("Shape of X_test:", X_test.shape)
print("Shape of y_train:", y_train.shape)
print("Shape of y_test:", y_test.shape)

Shape of X_train: (2666, 20)
Shape of X_test: (667, 20)
Shape of y_train: (2666,)
Shape of y_test: (667,)

In [5]:
# instantiate a Decision Tree model
xgb_model = XGBClassifier()

# fit the training data
xgb_model.fit(X_train, y_train)

# model prediction on the test dataset
y_pred_xgb = xgb_model.predict(X_test)

# compute the accuracy and display classification report
xgb_acc = accuracy_score(y_test, y_pred_xgb)
print("XGBoost model accuracy:", xgb_acc)

dec_report = classification_report(y_true=y_test, y_pred=y_pred_xgb)
print(dec_report)

XGBoost model accuracy: 0.9325337331334332
              precision    recall  f1-score   support

           0       0.94      0.99      0.96       566
           1       0.90      0.62      0.74       101

    accuracy                           0.93       667
   macro avg       0.92      0.81      0.85       667
weighted avg       0.93      0.93      0.93       667